name: temsah
description: Temsah Vehicle Presentation.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 2.0.0+2

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  video_player: ^2.8.1
  auto_size_text: ^3.0.0
  scroll_snap_list: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
<<<<<<< Updated upstream
    - assets/videos/intro_video.mp4
    - assets/images/logos/mogama3_logo.png
    - assets/images/logos/markabat_logo.png
    - assets/images/trailer/trailer.png
    - assets/images/temsah1/temsah1.png
    - assets/images/temsah2/temsah2.png
    - assets/images/temsah3/temsah3.png
    - assets/images/temsah4/temsah4.png
    - assets/images/temsah_bus/temsah-bus.png
    - assets/images/vip_armored_bus/bus.png
    - assets/images/light_temsah/light-temsah.png
    - assets/icons/axle.png
    - assets/icons/bandwidth.png
    - assets/icons/car.png
    - assets/icons/car-engine.png
    - assets/icons/cctv-camera.png
    - assets/icons/dimension.png
    - assets/icons/missiles.png
    - assets/icons/monitor.png
    - assets/icons/shield.png
    - assets/icons/weight.png
=======
    - assets/intro_video.mp4
    - assets/mogama3_logo.png
    - assets/markabat_logo.png
    - assets/trailer.png
    - assets/temsah1.png
    - assets/temsah2.png
    - assets/temsah3.png
    - assets/temsah4.png
    - assets/temsah6.png
    - assets/temsah-bus.png
    - assets/bus.png
    - assets/light-temsah.png
>>>>>>> Stashed changes

